services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
       CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    tty: true
    command: npm start
    depends_on:
      - backend
    container_name: job_app
    

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: job_db
      JWT_SECRET: ${JWT_SECRET}
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_db
    ports:
      - "5432:5432"
    volumes:
     - db-data:/var/lib/postgresql/data


volumes:
  db-data: